#PROPS
dataSource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/postgres
  username: postgres
  password: root
  dialect: org.hibernate.dialect.PostgreSQLDialect
  package: org.yakimovdenis.resttask.models

liquibase:
  enabled: false

application:
  dataQuantity: 100000
  charsCount: 50

